### PR TITLE
Our method on Lotka Volterra

### PR DESCRIPTION
**Pull request by Justinezgh**
Try to train our method on lv but doesn't work well [notebook](https://github.com/Justinezgh/SBI-Diff-Simulator/blob/u/Justinezgh/ourmethod/notebooks/Our_SBI_method_on_LV.ipynb)
image

### CODE REVIEW

**Comment by EiffL** [comment]
I'm looking at these :-) but the SmoothVSAffine should be a separate PR ;-) has nothing to do with LV

**Comment by EiffL** [comment]
I'm a bit confused >.< you used to have code that worked, right? like here: https://github.com/astrodeepnet/sbi_experiments/issues/21#issuecomment-1078473763

what is the difference?

**Comment by EiffL** [comment]
it looks like you were using a much simpler flow architecture.
```python
      chain = tfb.Chain([
            tfb.Exp(),
            tfb.Shift(shift = [-4.14,-7,-4.12,-7], name = 'shift1'),
            tfb.Scale(scale = 8, name='scale1'),
            tfb.RealNVP(2, bijector_fn=CustomCoupling_Compressor(y, name = 'b1')),
            tfb.Permute([3,2,1,0]),
            tfb.RealNVP(2, bijector_fn=CustomCoupling_Compressor(y, name = 'b2')),
            tfb.Permute([3,2,1,0]),
            tfb.RealNVP(2, bijector_fn=CustomCoupling_Compressor(y, name = 'b3')),           
            tfb.Permute([3,2,1,0]),
        ])
```

**Comment by Justinezgh** [comment]
yes so this was with the compression part and with the Exp() at the beginning, I don't really understand why but since I removed the Exp() it doesn't work well. And for some reason I have worse results with the new Lotka Volterra

**Comment by EiffL** [comment]
why are we using SiLu again? instead of sin ?

**Comment by Justinezgh** [comment]
Still trying to find the right architecture but results are better 
image

the architecture for this plot: 

```python 
bijector = partial(AffineSigmoidCoupling, 
                   layers = [560,560,560,560],
                   n_components = 64, 
                   activation = jax.nn.silu)

NF = partial(ConditionalRealNVP, n_layers = 4, bijector_fn = bijector)

nvp_nd = hk.without_apply_rng(hk.transform(lambda p,x : NF(4)(x).log_prob(p).squeeze()))
```

**Comment by EiffL** [comment]
Ok, so, here I would  suspect that you would get better performance if you had some shared neural network to compress the information. Something like:

```python
bijector = partial(AffineSigmoidCoupling, 
                   layers = [128,128],
                   n_components = 32, 
                   activation = jax.nn.silu)

NF = partial(ConditionalRealNVP, n_layers = 4, bijector_fn = bijector)

class Compressor:
  def __call__(self, x):
    net = relu(hk.Linear(x, 128))
    net = relu(hk.Linear(net, 128))
    net =  hk.Linear(net, d)

nvp_nd = hk.without_apply_rng(hk.transform(lambda p,x : NF(4)( Compressor()(x)).log_prob(p).squeeze()))
```

**Comment by Justinezgh** [comment]
yes ok :) but if we want to have the same architecture for scandal how can I use this ?

**Comment by EiffL** [comment]
Well, nothing prevents us from doing the same thing for scandal. But what matters above all else is to have at least one baseline result with out method that works ^^'

**Comment by EiffL** [comment]
What's the status of this PR compared to the other one?

**Comment by EiffL** [comment]
Bump

**Comment by Justinezgh** [comment]
hmm the purpose of this one was to make our method work, the other one is for azure scripts

**Pull request merged**
